# Generated by Django 4.0 on 2024-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=32, unique=True, verbose_name='用户ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='用户名')),
                ('mobile', models.CharField(default='', max_length=32, verbose_name='手机号码')),
                ('password', models.CharField(default='', max_length=64, verbose_name='密码')),
                ('status', models.CharField(default='used', max_length=32, verbose_name='用户状态')),
                ('role', models.IntegerField(verbose_name='管理员0|审核员1|运营人员2')),
                ('start_time', models.DateTimeField(verbose_name='账号开始使用时间')),
                ('end_time', models.DateTimeField(verbose_name='账号结束使用时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('token', models.CharField(default='', max_length=32, verbose_name='token')),
                ('token_exp', models.DateTimeField(default='', null=True, verbose_name='token 过期时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
