# Generated by Django 4.0 on 2024-07-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=64, verbose_name='标题')),
                ('name', models.CharField(default='', max_length=64, verbose_name='文件名称')),
                ('type', models.CharField(default='', max_length=32, verbose_name='文件类型')),
                ('path', models.CharField(default='', max_length=64, verbose_name='文件路径')),
                ('time_limite', models.CharField(default='', max_length=32, verbose_name='使用限制')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('desc', models.CharField(default='', max_length=64, verbose_name='描述信息')),
            ],
            options={
                'db_table': 'tong_media',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.IntegerField(default=0, verbose_name='是否立即生效'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
