# Generated by Django 4.0 on 2024-05-19 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_token_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 13, 52, 27, 413607), null=True, verbose_name='token 过期时间'),
        ),
    ]
