# Generated by Django 4.0 on 2024-07-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_media_user_tag_user_user_name_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
