# Generated by Django 4.0 on 2024-05-19 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_token_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='账号结束使用时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default='', verbose_name='管理员0|审核员1|运营人员2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='账号开始使用时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 13, 55, 42, 85267), null=True, verbose_name='token 过期时间'),
        ),
    ]
