# Generated by Django 4.0 on 2024-05-19 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_end_time_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=0, verbose_name='管理员0|审核员1|运营人员2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 13, 57, 12, 439575), null=True, verbose_name='token 过期时间'),
        ),
    ]
